### ISSUE TITLE
Contributing to the Magazine?

### ISSUE THREAD

**Issue by Alex-Keyes** [nixers-projects/magazine#1]
Hey Venam,

How do you plan on getting submission for articles? Is everybody free to submit something?

**Comment by venam** [comment]
⁣Unfortunately, the magazine didn't take off as we were hoping it would.

It required too much involvement and not many were interested in putting in the efforts (This happens with any group endeavors.)

What I propose instead is writing some content to feature or simply emailing me links so that I could include them in  the newsletter.

Let's consider the newsletter our magazine for now.

Thanks for caring about the projects!

**Comment by Alex-Keyes** [comment]
Fair enough.   Do you have information about contributing to the newsletter?  I'd like to write some content about unix and help contribute to the nixers community

**Comment by rocx** [comment]
The [thread for the newsletter][1] should go over the process of contributing...somewhere. If not, feel free to drop @venam a line about what you'd like to suggest.

[1]: https://nixers.net/showthread.php?tid=2022

**Comment by Alex-Keyes** [comment]
@rocx thanks for the heads up bro!
